language: cpp

dist: bionic

matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - BUILD_TYPE='release'
    - os: linux
      addons:
        apt:
          packages:
            - lcov
      env:
        - BUILD_TYPE='debug'
        - COVERAGE='--coverage'

env:
  global:
    - LC_ALL="en_US.UTF-8"
    - LANG="en_US.UTF-8"
    - LANGUAGE="en_US.UTF-8"
    - PYTHONIOENCODING=UTF-8
    - OMP_NUM_THREADS=1

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create --name vampyr python=3.6 -c conda-forge
  - conda env update --name vampyr --file environment.yml

before_script:
  - test -n $CXX && unset CXX

script:
  - conda activate vampyr
  - echo ${CXX}
  - ./.ci/report_versions.sh
  - >
      python ./setup \
             --type=${BUILD_TYPE} \
             --cxx=${CONDA_PREFIX}/bin/x86_64-conda_cos6-linux-gnu-g++ \
             --generator=Ninja \
             --prefix=$HOME/Software/VAMPyR \
             ${COVERAGE} \
             --cmake-options="-DCMAKE_PREFIX_PATH=${CONDA_PREFIX} -DPYTHON_EXECUTABLE=${CONDA_PREFIX}/bin/python -DCMAKE_VERBOSE_MAKEFILE=ON"
  - cd build
  - cmake --build . --target install -- -v -d stats
  - ctest --output-on-failure --verbose
  - conda deactivate

after_success:
  - |
    if [[ "${COVERAGE}" = "--coverage" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      lcov --version
      lcov --directory build/vampyr/ --capture --output-file coverage.info
      lcov --remove coverage.info '/usr/*' --output-file coverage.info
      lcov --list coverage.info
      bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
    fi
