version: 2
variables:
  ubuntu-1804: &ubuntu-1804
    docker:
      - image: quay.io/metamr/circleci_ubuntu-18.04-conda:b31cfce
        name: tsubame
        user: merzbow
    working_directory: ~/vampyr
  setup: &setup
    run:
      name: Create Conda environment
      command: |
        conda create --name vampyr python=3.6 -c conda-forge
        conda env update --name vampyr --file environment.yml
  configure: &configure
    run:
      name: Configuring
      command: |
        source activate vampyr
        python ./setup \
          --type=release \
          --cxx=${CONDA_PREFIX}/bin/x86_64-conda_cos6-linux-gnu-g++ \
          --generator=Ninja \
          --prefix=$HOME/Software/VAMPyR \
          --cmake-options="-DCMAKE_PREFIX_PATH=${CONDA_PREFIX} -DCMAKE_VERBOSE_MAKEFILE=ON"
  build: &build
    run:
      name: Building and installing
      command: |
        source activate vampyr
        cmake --build build --target install -- -j 1 -d stats
  tests: &tests
    run:
      name: Testing
      command: |
        source activate vampyr
        cd build
        ctest --output-on-failure --verbose

jobs:
  py3:
    <<: *ubuntu-1804
    steps:
      - checkout
      - *setup
      - *configure
      - *build
      - *tests

workflows:
  version: 2
  build:
    jobs:
      - py3
