version: 2
variables:
  ubuntu-1804: &ubuntu-1804
    docker:
      - image: quay.io/metamr/circleci_ubuntu-18.04-conda
        name: tsubame
        user: merzbow
    working_directory: ~/vampyr
  setup: &setup
    run:
      name: Create Conda environment
      command: |
        conda create --name vampyr python=3.6 -c conda-forge
        conda env update --name vampyr --file environment.yml
  configure-serial: &configure-serial
    run:
      name: Configuring serial
      command: |
        source activate vampyr
        python ./setup \
          --type=release \
          --cxx=g++ \
          --generator=Ninja \
          --prefix=$HOME/Software/VAMPyR \
          --omp \
          --cmake-options="-DCMAKE_PREFIX_PATH=${CONDA_PREFIX} -DCMAKE_VERBOSE_MAKEFILE=ON"
  build: &build
    run:
      name: Building and installing
      command: |
        source activate vampyr
        cmake --build build --target install -- -j 1 -d stats
  tests: &tests
    run:
      name: Testing
      command: |
        source activate vampyr
        cd build
        ctest --output-on-failure --verbose

jobs:
  serial-py3:
    <<: *ubuntu-1804
    steps:
      - checkout
      - *setup
      - *configure-serial
      - *build
      - *tests

workflows:
  version: 2
  build:
    jobs:
      - serial-py3
