on: [push]

name: Release VAMPyR

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v2
      - name: Releases via Palisade
        run: |
          docker run --rm --name palisade -v $(pwd):/workspace -e GITHUB_TOKEN -e GITHUB_REF -e GITHUB_REPOSITORY --workdir /workspace lightspeedhq/palisade palisade github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
