name: Install VAMPyR with pip

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.11"

    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pip install
      run: |
        python -m pip install -vvv .[test]

    - name: Import VAMPyR
      run: |
        python -c "import vampyr; print(vampyr.__version__); print(vampyr.mrcpp_version())"

    - name: Test with pytest
      run: |
        python -m pytest -rws -v --pyargs vampyr
